<a href="https://colab.research.google.com/github/nikasvesko/repic/blob/main/0502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#za loadanje i manipulaciju je pandas
#plotanje seaborn i matlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
dataset = pd.read_csv('https://raw.githubusercontent.com/bio-chem-info/python_course/refs/heads/main/preprocess_data.csv')

In [7]:
a = dataset.tail(2).T #uzimamo dva zadnja i mijenjamo retke za stupce

In [10]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [8]:
a #transponirani dio .T #pipeline operator je .

,8,9
Country,Germany,France
Age,50.0,37.0
Salary,83000.0,67000.0
Purchased,No,Yes


In [9]:
dataset.head()

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [11]:
dataset.head(2)

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes


In [48]:
#indeksiranje
#dohvacanje dijela podataka
X= dataset.iloc[:,:-1] #sve osim zadnjeg stupca
Y= dataset.iloc[:,-1] #ovo znači samo zadnji stupac

In [49]:
X

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [45]:
X.fillna(-99)

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,-99.0
5,France,35.0,58000.0
6,Spain,-99.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [13]:
Y

,Purchased
0,No
1,Yes
2,No
3,No
4,Yes
5,Yes
6,No
7,Yes
8,No
9,Yes


In [38]:
X

In [15]:
X.describe() #statistika df

,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [ ]:
#NaN- not a number

In [16]:
X.isna().sum() #filtrira missing values i zbraja ih

,0
Country,0
Age,1
Salary,1


In [17]:
X

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [27]:
X.fillna(0) #popunili smo na s 0, nismo ga promijenili samo smo ga ispisali, ako smo ga htjeli ostavit

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,0.0
5,France,35.0,58000.0
6,Spain,0.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [30]:
X.fillna(-99, inplace= True)

In [31]:
X

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,0.0
5,France,35.0,58000.0
6,Spain,0.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [21]:
X1= X.fillna(0)
X1

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,0.0
5,France,35.0,58000.0
6,Spain,0.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [46]:
X=dataset.fillna(-99) #definiram X opet
X

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,-99.0,Yes
5,France,35.0,58000.0,Yes
6,Spain,-99.0,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [60]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan,
                       strategy='median')
imputer #kreiran simple imputer koji ce zamijeniti nan s medijanom

SimpleImputer(strategy='median')

In [51]:
imputer.fit(X[['Age', 'Salary']])
imputer.statistics_    #uči medijane

array([3.8e+01, 6.1e+04])

In [52]:
X[['Age', 'Salary']].median() #vanjska uglata je indeksiranje, a unutarnja je lista

,0
Age,38.0
Salary,61000.0


In [55]:
X_imputed = imputer.transform(X[['Age', 'Salary']])    #ovako ce to promijeniti, s transform na prazna polja

In [56]:
imputer

SimpleImputer(strategy='median')

In [57]:
X_imputed

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [58]:
X_imp = pd.DataFrame(data = X_imputed,      #kako od matrice u df, sigurno na ispitu
                     columns= ['Age', 'Salary'],
                     index= X.index)
X_imp

,Age,Salary
0,44.0,72000.0
1,27.0,48000.0
2,30.0,54000.0
3,38.0,61000.0
4,40.0,61000.0
5,35.0,58000.0
6,38.0,52000.0
7,48.0,79000.0
8,50.0,83000.0
9,37.0,67000.0


In [59]:
X_imp.median()

,0
Age,38.0
Salary,61000.0


In [61]:
df = pd.DataFrame({
    "A": [1, -0.666, 3, 4],
    "B": [-0.666, 5, 6, -0.666],
    "C": [7, 8, -0.666, 10]
})
df

,A,B,C
0,1.000,-0.666,7.000
1,-0.666,5.000,8.000
2,3.000,6.000,-0.666
3,4.000,-0.666,10.000


In [91]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values= -0.666,
                       strategy='median')
imputer

SimpleImputer(missing_values=-0.666, strategy='median')

In [92]:
imputer.fit(df[['A', 'B', 'C']])
imputer.statistics_

array([3. , 5.5, 8. ])

In [93]:
df_imputed = imputer.transform(df[['A', 'B', 'C']])

In [94]:
df_imputed

array([[ 1. ,  5.5,  7. ],
       [ 3. ,  5. ,  8. ],
       [ 3. ,  6. ,  8. ],
       [ 4. ,  5.5, 10. ]])

In [95]:
#nenumerički podatci u numeričke #dobivano nove stupce koji su ispunjeni 0 i 1

In [98]:
#izbaci jednu drzavu jer ako nisu ove dve onda je ta treca
X_encoded= pd.get_dummies(X, columns=['Country'])
X_encoded

,Age,Salary,Country_France,Country_Germany,Country_Spain
0,44.0,72000.0,True,False,False
1,27.0,48000.0,False,False,True
2,30.0,54000.0,False,True,False
3,38.0,61000.0,False,False,True
4,40.0,NaN,False,True,False
5,35.0,58000.0,True,False,False
6,NaN,52000.0,False,False,True
7,48.0,79000.0,True,False,False
8,50.0,83000.0,False,True,False
9,37.0,67000.0,True,False,False


In [99]:
X_encoded = X_encoded.replace({True:1, False:0}) #dictionaries da zamijenimo ti true and false s binarnim!
X_encoded  #sad je sve numeričko!!!!!!!!!!!!!!!!

/tmp/ipython-input-2051129379.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_encoded = X_encoded.replace({True:1, False:0})


,Age,Salary,Country_France,Country_Germany,Country_Spain
0,44.0,72000.0,1,0,0
1,27.0,48000.0,0,0,1
2,30.0,54000.0,0,1,0
3,38.0,61000.0,0,0,1
4,40.0,NaN,0,1,0
5,35.0,58000.0,1,0,0
6,NaN,52000.0,0,0,1
7,48.0,79000.0,1,0,0
8,50.0,83000.0,0,1,0
9,37.0,67000.0,1,0,0


In [100]:
Y

,Purchased
0,No
1,Yes
2,No
3,No
4,Yes
5,Yes
6,No
7,Yes
8,No
9,Yes


In [101]:
Y['Purchased'] = Y['Purchased'].map({'Yes': 1, 'No': 0})

KeyError: 'Purchased'

In [113]:
Y_encoded = pd.get_dummies(Y, drop_first=True)
Y_encoded      #Kako preimenovati stupac

,Yes
0,False
1,True
2,False
3,False
4,True
5,True
6,False
7,True
8,False
9,True


In [115]:
Y_encoded.columns = ['kupnja']
Y_encoded

,kupnja
0,False
1,True
2,False
3,False
4,True
5,True
6,False
7,True
8,False
9,True


In [112]:
Y_encoded.replace({False:0, True:1}, inplace=True)

In [ ]:
#zavisne varijable

In [116]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_encoded, Y_encoded, test_size = 0.25,
                                                    random_state=1)

In [117]:
print(X_train)

    Age   Salary  Country_France  Country_Germany  Country_Spain
4  40.0      NaN               0                1              0
0  44.0  72000.0               1                0              0
3  38.0  61000.0               0                0              1
1  27.0  48000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
5  35.0  58000.0               1                0              0


In [118]:
X_test

,Age,Salary,Country_France,Country_Germany,Country_Spain
2,30.0,54000.0,0,1,0
9,37.0,67000.0,1,0,0
6,NaN,52000.0,0,0,1


In [119]:
Y_train

,kupnja
4,True
0,False
3,False
1,True
7,True
8,False
5,True


In [120]:
Y_test


,kupnja
2,False
9,True
6,False


In [127]:
#skaliranje podataka, radi razlicitih skala podataka, MINMAX svodi sve varijable od 0 do 1, ali razmaci ostaju isti
from sklearn.preprocessing import StandardScaler
sc = StandardScaler ()
sc


StandardScaler()

In [130]:
sc.mean_

array([4.02857143e+01, 6.68333333e+04, 4.28571429e-01, 2.85714286e-01,
       2.85714286e-01])

In [141]:
X_train_sc = sc.fit_transform(X_train)  #fittransform, istovremeno uči i primjenjuje
X_test_sc= sc.transform(X_test)


X_train_sc = pd.DataFrame(
    sc.fit_transform(X_train),
    columns=X_train.columns
)

X_train_sc.describe()

,Age,Salary,Country_France,Country_Germany,Country_Spain
count,7.000000e+00,6.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
mean,1.427430e-16,4.070818e-16,3.172066e-17,3.172066e-17,3.172066e-17
std,1.080123e+00,1.095445e+00,1.080123e+00,1.080123e+00,1.080123e+00
min,-1.809325e+00,-1.535320e+00,-8.660254e-01,-6.324555e-01,-6.324555e-01
25%,-5.155603e-01,-6.589650e-01,-8.660254e-01,-6.324555e-01,-6.324555e-01
50%,-3.891021e-02,-2.717381e-02,-8.660254e-01,-6.324555e-01,-6.324555e-01
75%,7.782042e-01,8.491816e-01,1.154701e+00,4.743416e-01,4.743416e-01
max,1.322947e+00,1.317930e+00,1.154701e+00,1.581139e+00,1.581139e+00


In [136]:
X_train

,Age,Salary,Country_France,Country_Germany,Country_Spain
4,40.0,NaN,0,1,0
0,44.0,72000.0,1,0,0
3,38.0,61000.0,0,0,1
1,27.0,48000.0,0,0,1
7,48.0,79000.0,1,0,0
8,50.0,83000.0,0,1,0
5,35.0,58000.0,1,0,0


In [132]:
sc.scale_

array([7.34291273e+00, 1.22667120e+04, 4.94871659e-01, 4.51753951e-01,
       4.51753951e-01])

In [134]:
X_train.var()

,0
Age,6.290476e+01
Salary,1.805667e+08
Country_France,2.857143e-01
Country_Germany,2.380952e-01
Country_Spain,2.380952e-01


In [133]:
X_train.var(axis=0, ddof=0)


,0
Age,5.391837e+01
Salary,1.504722e+08
Country_France,2.448980e-01
Country_Germany,2.040816e-01
Country_Spain,2.040816e-01


In [138]:
X_train.describe()

,Age,Salary,Country_France,Country_Germany,Country_Spain
count,7.000000,6.000000,7.000000,7.000000,7.000000
mean,40.285714,66833.333333,0.428571,0.285714,0.285714
std,7.931252,13437.509690,0.534522,0.487950,0.487950
min,27.000000,48000.000000,0.000000,0.000000,0.000000
25%,36.500000,58750.000000,0.000000,0.000000,0.000000
50%,40.000000,66500.000000,0.000000,0.000000,0.000000
75%,46.000000,77250.000000,1.000000,0.500000,0.500000
max,50.000000,83000.000000,1.000000,1.000000,1.000000


In [142]:
X_train_sc.describe()

,Age,Salary,Country_France,Country_Germany,Country_Spain
count,7.000000e+00,6.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
mean,1.427430e-16,4.070818e-16,3.172066e-17,3.172066e-17,3.172066e-17
std,1.080123e+00,1.095445e+00,1.080123e+00,1.080123e+00,1.080123e+00
min,-1.809325e+00,-1.535320e+00,-8.660254e-01,-6.324555e-01,-6.324555e-01
25%,-5.155603e-01,-6.589650e-01,-8.660254e-01,-6.324555e-01,-6.324555e-01
50%,-3.891021e-02,-2.717381e-02,-8.660254e-01,-6.324555e-01,-6.324555e-01
75%,7.782042e-01,8.491816e-01,1.154701e+00,4.743416e-01,4.743416e-01
max,1.322947e+00,1.317930e+00,1.154701e+00,1.581139e+00,1.581139e+00


In [149]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler ()
mm

MinMaxScaler()

In [150]:
X_train_mm = mm.fit_transform(X_train)  #fittransform, istovremeno uči i primjenjuje
X_test_sc= mm.transform(X_test)

In [151]:
mm.min_

array([-1.17391304, -1.37142857,  0.        ,  0.        ,  0.        ])